version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          TZ: "America/Los_Angeles"
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests (exluding integration tests)
      - run: npm run ci-coverage
