name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run CI
        run: |
          npm install
          npm run lint
          npm run test -- --coverage src/tests/snapshot src/tests/unit
          npm run semantic-release
