name: Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Run CI
        run: |
          npm ci
          npm run lint
          npm run test -- --coverage src/tests/snapshot src/tests/unit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Auth NPM
        run: npm profile get
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
